### ISSUE TITLE
New build with newer numpy

### ISSUE THREAD

**Issue by ocefpaf** [conda-forge/fatiando-feedstock#1]
@leouieda now that we got a [version](http://anaconda.org/conda-forge/fatiando/files) with `numpy 1.9` and `mayavi` you can, if you think it is useful, issue a new build number by removing `mayavi` and switching `numpy 1.9.*` to `numpy x.x`.

That would give people who do not want `mayavi` to install `fatiando` with a newer `numpy` while still leaving a restricted `numpy 1.9`+`mayavi` version on the channel for those who need it.

**Comment by leouieda** [comment]
@ocefpaf great I was actually wanting just that for one of my own projects.

If I do this on another branch, will the CI build and upload to anaconda.org? Otherwise I'd have to put mayavi back for the next release and then for the next and so on. So my idea would be to have a `no-mayavi` branch without the Mayavi requirement that I'd rebase for new releases.

**Comment by ocefpaf** [comment]
> If I do this on another branch, will the CI build and upload to anaconda.org? 

Yep. We do manage different version like this. See the [gdal-feedstock](https://github.com/conda-forge/gdal-feedstock/).

> Otherwise I'd have to put mayavi back for the next release and then for the next and so on.

That is an alternative but I'd rather use the branching. (Unless you plan to drop `mayavi` in the next release of fatiando.)

**Comment by leouieda** [comment]
>  (Unless you plan to drop mayavi in the next release of fatiando.)

That would be the dream...

OK, I'll go with the branching then!

**Comment by leouieda** [comment]
@ocefpaf when time comes for a new release, do you rebase the branch or just copy over the changes in a new commit? Seems like the second option is easier.

**Comment by ocefpaf** [comment]
> do you rebase the branch or just copy over the changes in a new commit? Seems like the second option is easier.

We do the second in `gdal` not only b/c it is easier but also b/c the branches are completely out of sync and rebasing does not make much sense. Here the case is slightly different b/c it is not a different version but I believe the same logic would apply.

At the end of the day it is up to you as maintainer to choose the easier path as you will be doing that :wink:

**Comment by ocefpaf** [comment]
Done in #2 

Thanks @leouieda!

**Comment by leouieda** [comment]
OK, thanks for all the pointers @ocefpaf
